spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            mvc:
                routes:
                 - id : products
                   uri: 
                    http://localhost:8083/
                   predicates:
                    - Path=/product-service/**
            default-filters:
                - TokenRelay
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: gateway-service
                        client-secret: SqTAwyQ3UbtR68klC8Buq4IYWOr0Hl6c
                        scope: openid
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/ecommerceversart

server:
    port: 8082
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:8081/eureka/
