spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            mvc:
                routes:
                 - id : products
                   uri: 
                    http://localhost:8083/
                   predicates:
                    - Path=/product-service/**
                   
                    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/ecommerce-versart

server:
    port: 8082
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:8081/eureka/
