spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            mvc:
                routes:
                 - id : authentication
                   uri: 
                    http://localhost:8083/
                   predicates:
                    - Path=/auth/**


server:
    port: 8082
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:8081/eureka/
