version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: postgresql
    environment:
       POSTGRES_DB: products
       POSTGRES_PASSWORD: secret
       POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - product_data:/var/lib/postgresql/data
volumes:
  product_data: